/* tslint:disable */
/* eslint-disable */
/**
 * Employees
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Employee {
    'id': number;
    'name': string;
    'photo': string;
    'phone': string;
    /**
     * Localized gender label (e.g. \"Мужчина\", \"Женщина\")
     */
    'gender': string;
    /**
     * Localized position label (e.g. \"Frontend-разработчик\")
     */
    'position': string;
    'stack': Array<string>;
    /**
     * Localized date string
     */
    'birthdate': string;
    /**
     * Localized date string
     */
    'dateOfEmployment': string;
}

export const Gender = {
    Male: 'Male',
    Female: 'Female'
} as const;

export type Gender = typeof Gender[keyof typeof Gender];



export const Position = {
    Frontend: 'Frontend',
    Backend: 'Backend',
    Analyst: 'Analyst',
    Manager: 'Manager',
    Designer: 'Designer'
} as const;

export type Position = typeof Position[keyof typeof Position];



export const Technology = {
    CSharp: 'CSharp',
    React: 'React',
    Java: 'Java',
    Php: 'PHP',
    Figma: 'Figma',
    Word: 'Word'
} as const;

export type Technology = typeof Technology[keyof typeof Technology];



/**
 * EmployeeApi - axios parameter creator
 */
export const EmployeeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {string} [name] 
         * @param {Array<Gender>} [gender] 
         * @param {Array<Position>} [position] 
         * @param {Array<Technology>} [stack] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeGet: async (page?: number, count?: number, name?: string, gender?: Array<Gender>, position?: Array<Position>, stack?: Array<Technology>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Employee`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['Page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['Count'] = count;
            }

            if (name !== undefined) {
                localVarQueryParameter['Name'] = name;
            }

            if (gender) {
                localVarQueryParameter['Gender'] = gender;
            }

            if (position) {
                localVarQueryParameter['Position'] = position;
            }

            if (stack) {
                localVarQueryParameter['Stack'] = stack;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiEmployeeIdGet', 'id', id)
            const localVarPath = `/api/Employee/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeApi - functional programming interface
 */
export const EmployeeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {string} [name] 
         * @param {Array<Gender>} [gender] 
         * @param {Array<Position>} [position] 
         * @param {Array<Technology>} [stack] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEmployeeGet(page?: number, count?: number, name?: string, gender?: Array<Gender>, position?: Array<Position>, stack?: Array<Technology>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Employee>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEmployeeGet(page, count, name, gender, position, stack, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmployeeApi.apiEmployeeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEmployeeIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Employee>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEmployeeIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmployeeApi.apiEmployeeIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EmployeeApi - factory interface
 */
export const EmployeeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {string} [name] 
         * @param {Array<Gender>} [gender] 
         * @param {Array<Position>} [position] 
         * @param {Array<Technology>} [stack] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeGet(page?: number, count?: number, name?: string, gender?: Array<Gender>, position?: Array<Position>, stack?: Array<Technology>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Employee>> {
            return localVarFp.apiEmployeeGet(page, count, name, gender, position, stack, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Employee> {
            return localVarFp.apiEmployeeIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmployeeApi - object-oriented interface
 */
export class EmployeeApi extends BaseAPI {
    /**
     * 
     * @param {number} [page] 
     * @param {number} [count] 
     * @param {string} [name] 
     * @param {Array<Gender>} [gender] 
     * @param {Array<Position>} [position] 
     * @param {Array<Technology>} [stack] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiEmployeeGet(page?: number, count?: number, name?: string, gender?: Array<Gender>, position?: Array<Position>, stack?: Array<Technology>, options?: RawAxiosRequestConfig) {
        return EmployeeApiFp(this.configuration).apiEmployeeGet(page, count, name, gender, position, stack, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiEmployeeIdGet(id: number, options?: RawAxiosRequestConfig) {
        return EmployeeApiFp(this.configuration).apiEmployeeIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}



